# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import Callable, overload

from cloudcoil.apimachinery import (
    Status,
)
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)


class Fields(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Fields"]:
            return Fields

        def build(self) -> "Fields":
            return Fields(**self._attrs)

    class BuilderContext(BuilderContextBase["Fields.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Fields.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Fields."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Fields", Builder]:
        return GenericListBuilder[Fields, Fields.Builder]()

    pass


class Initializer(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Initializer"]:
            return Initializer

        def build(self) -> "Initializer":
            return Initializer(**self._attrs)

        def name(self, value: str, /) -> Self:
            "name of the process that is responsible for initializing this object."
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["Initializer.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Initializer.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Initializer."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Initializer", Builder]:
        return GenericListBuilder[Initializer, Initializer.Builder]()

    name: str
    "name of the process that is responsible for initializing this object."


class Initializers(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Initializers"]:
            return Initializers

        def build(self) -> "Initializers":
            return Initializers(**self._attrs)

        @overload
        def pending(self, value_or_callback: list[Initializer], /) -> "Initializers.Builder": ...

        @overload
        def pending(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[Initializer, Initializer.Builder]],
                GenericListBuilder[Initializer, Initializer.Builder] | list[Initializer],
            ],
            /,
        ) -> "Initializers.Builder": ...

        @overload
        def pending(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[Initializer.Builder]: ...

        def pending(self, value_or_callback=UNSET, /):
            "Pending is a list of initializers that must execute in order before this object is visible. When the last pending initializer is removed, and no failing result is set, the initializers struct will be set to nil and the object is considered as initialized and visible to all clients."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[Initializer.Builder]()
                context._parent_builder = self
                context._field_name = "pending"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Initializer.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("pending", value)

        @overload
        def result(self, value_or_callback: Status | None, /) -> "Initializers.Builder": ...

        @overload
        def result(
            self,
            value_or_callback: Callable[[Status.Builder], Status.Builder | Status],
            /,
        ) -> "Initializers.Builder": ...

        @overload
        def result(self, value_or_callback: Never = ...) -> "Status.BuilderContext": ...

        def result(self, value_or_callback=UNSET, /):
            "If result is set with the Failure field, the object will be persisted to storage and then deleted, ensuring that other clients can observe the deletion."
            if self._in_context and value_or_callback is UNSET:
                context = Status.BuilderContext()
                context._parent_builder = self
                context._field_name = "result"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Status.builder())
                if isinstance(output, Status.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("result", value)

    class BuilderContext(BuilderContextBase["Initializers.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Initializers.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Initializers."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Initializers", Builder]:
        return GenericListBuilder[Initializers, Initializers.Builder]()

    pending: list[Initializer]
    "Pending is a list of initializers that must execute in order before this object is visible. When the last pending initializer is removed, and no failing result is set, the initializers struct will be set to nil and the object is considered as initialized and visible to all clients."
    result: Status | None = None
    "If result is set with the Failure field, the object will be persisted to storage and then deleted, ensuring that other clients can observe the deletion."
