# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.kpack.kpack.build.v1alpha1 import Build as _Resource0
    from cloudcoil.models.kpack.kpack.build.v1alpha1 import BuilderResource as _Resource2
    from cloudcoil.models.kpack.kpack.build.v1alpha1 import ClusterBuilder as _Resource5
    from cloudcoil.models.kpack.kpack.build.v1alpha1 import ClusterStack as _Resource9
    from cloudcoil.models.kpack.kpack.build.v1alpha1 import ClusterStore as _Resource11
    from cloudcoil.models.kpack.kpack.build.v1alpha1 import Image as _Resource13
    from cloudcoil.models.kpack.kpack.build.v1alpha1 import SourceResolver as _Resource15
    from cloudcoil.models.kpack.kpack.build.v1alpha2 import Build as _Resource1
    from cloudcoil.models.kpack.kpack.build.v1alpha2 import BuilderResource as _Resource3
    from cloudcoil.models.kpack.kpack.build.v1alpha2 import Buildpack as _Resource4
    from cloudcoil.models.kpack.kpack.build.v1alpha2 import ClusterBuilder as _Resource6
    from cloudcoil.models.kpack.kpack.build.v1alpha2 import ClusterBuildpack as _Resource7
    from cloudcoil.models.kpack.kpack.build.v1alpha2 import ClusterLifecycle as _Resource8
    from cloudcoil.models.kpack.kpack.build.v1alpha2 import ClusterStack as _Resource10
    from cloudcoil.models.kpack.kpack.build.v1alpha2 import ClusterStore as _Resource12
    from cloudcoil.models.kpack.kpack.build.v1alpha2 import Image as _Resource14
    from cloudcoil.models.kpack.kpack.build.v1alpha2 import SourceResolver as _Resource16

_MODELS = {
    ("Build", "kpack.io/v1alpha1"): ("cloudcoil.models.kpack.kpack.build.v1alpha1", "Build"),
    ("Build", "kpack.io/v1alpha2"): ("cloudcoil.models.kpack.kpack.build.v1alpha2", "Build"),
    ("Builder", "kpack.io/v1alpha1"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha1",
        "BuilderResource",
    ),
    ("Builder", "kpack.io/v1alpha2"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha2",
        "BuilderResource",
    ),
    ("Buildpack", "kpack.io/v1alpha2"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha2",
        "Buildpack",
    ),
    ("Buildpack", ""): ("cloudcoil.models.kpack.kpack.build.v1alpha2", "Buildpack"),
    ("ClusterBuilder", "kpack.io/v1alpha1"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha1",
        "ClusterBuilder",
    ),
    ("ClusterBuilder", "kpack.io/v1alpha2"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha2",
        "ClusterBuilder",
    ),
    ("ClusterBuildpack", "kpack.io/v1alpha2"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha2",
        "ClusterBuildpack",
    ),
    ("ClusterBuildpack", ""): ("cloudcoil.models.kpack.kpack.build.v1alpha2", "ClusterBuildpack"),
    ("ClusterLifecycle", "kpack.io/v1alpha2"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha2",
        "ClusterLifecycle",
    ),
    ("ClusterLifecycle", ""): ("cloudcoil.models.kpack.kpack.build.v1alpha2", "ClusterLifecycle"),
    ("ClusterStack", "kpack.io/v1alpha1"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha1",
        "ClusterStack",
    ),
    ("ClusterStack", "kpack.io/v1alpha2"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha2",
        "ClusterStack",
    ),
    ("ClusterStore", "kpack.io/v1alpha1"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha1",
        "ClusterStore",
    ),
    ("ClusterStore", "kpack.io/v1alpha2"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha2",
        "ClusterStore",
    ),
    ("Image", "kpack.io/v1alpha1"): ("cloudcoil.models.kpack.kpack.build.v1alpha1", "Image"),
    ("Image", "kpack.io/v1alpha2"): ("cloudcoil.models.kpack.kpack.build.v1alpha2", "Image"),
    ("SourceResolver", "kpack.io/v1alpha1"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha1",
        "SourceResolver",
    ),
    ("SourceResolver", "kpack.io/v1alpha2"): (
        "cloudcoil.models.kpack.kpack.build.v1alpha2",
        "SourceResolver",
    ),
}


@overload
def get_model(
    kind: Literal["Build"], *, api_version: Literal["kpack.io/v1alpha1"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["Build"], *, api_version: Literal["kpack.io/v1alpha2"]
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["Builder"], *, api_version: Literal["kpack.io/v1alpha1"]
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["Builder"], *, api_version: Literal["kpack.io/v1alpha2"]
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["Buildpack"], *, api_version: Literal["kpack.io/v1alpha2"]
) -> type[_Resource4]: ...


@overload
def get_model(kind: Literal["Buildpack"], *, api_version: Literal[""] = "") -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["ClusterBuilder"], *, api_version: Literal["kpack.io/v1alpha1"]
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["ClusterBuilder"], *, api_version: Literal["kpack.io/v1alpha2"]
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["ClusterBuildpack"], *, api_version: Literal["kpack.io/v1alpha2"]
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["ClusterBuildpack"], *, api_version: Literal[""] = ""
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["ClusterLifecycle"], *, api_version: Literal["kpack.io/v1alpha2"]
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["ClusterLifecycle"], *, api_version: Literal[""] = ""
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["ClusterStack"], *, api_version: Literal["kpack.io/v1alpha1"]
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["ClusterStack"], *, api_version: Literal["kpack.io/v1alpha2"]
) -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["ClusterStore"], *, api_version: Literal["kpack.io/v1alpha1"]
) -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["ClusterStore"], *, api_version: Literal["kpack.io/v1alpha2"]
) -> type[_Resource12]: ...


@overload
def get_model(
    kind: Literal["Image"], *, api_version: Literal["kpack.io/v1alpha1"]
) -> type[_Resource13]: ...


@overload
def get_model(
    kind: Literal["Image"], *, api_version: Literal["kpack.io/v1alpha2"]
) -> type[_Resource14]: ...


@overload
def get_model(
    kind: Literal["SourceResolver"], *, api_version: Literal["kpack.io/v1alpha1"]
) -> type[_Resource15]: ...


@overload
def get_model(
    kind: Literal["SourceResolver"], *, api_version: Literal["kpack.io/v1alpha2"]
) -> type[_Resource16]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
