# Generated by cloudcoil-model-codegen v0.7.0
# DO NOT EDIT

from typing import Annotated, Callable, overload

from cloudcoil.apimachinery import Time
from cloudcoil.models.kubernetes.core.v1 import (
    LocalObjectReference,
)
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from pydantic import Field


class Blob(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Blob"]:
            return Blob

        def build(self) -> "Blob":
            return Blob(**self._attrs)

        def auth(self, value: str | None, /) -> Self:
            return self._set("auth", value)

        def strip_components(self, value: int | None, /) -> Self:
            return self._set("strip_components", value)

        def url(self, value: str, /) -> Self:
            return self._set("url", value)

    class BuilderContext(BuilderContextBase["Blob.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Blob.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Blob."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Blob", Builder]:
        return GenericListBuilder[Blob, Blob.Builder]()

    auth: str | None = None
    strip_components: Annotated[int | None, Field(alias="stripComponents")] = None
    url: str = ""


class BuildBuilderSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["BuildBuilderSpec"]:
            return BuildBuilderSpec

        def build(self) -> "BuildBuilderSpec":
            return BuildBuilderSpec(**self._attrs)

        def image(self, value: str | None, /) -> Self:
            return self._set("image", value)

        @overload
        def image_pull_secrets(
            self, value_or_callback: list[LocalObjectReference] | None, /
        ) -> "BuildBuilderSpec.Builder": ...

        @overload
        def image_pull_secrets(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[LocalObjectReference, LocalObjectReference.Builder]],
                GenericListBuilder[LocalObjectReference, LocalObjectReference.Builder]
                | list[LocalObjectReference],
            ],
            /,
        ) -> "BuildBuilderSpec.Builder": ...

        @overload
        def image_pull_secrets(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[LocalObjectReference.Builder]: ...

        def image_pull_secrets(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[LocalObjectReference.Builder]()
                context._parent_builder = self
                context._field_name = "image_pull_secrets"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(LocalObjectReference.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("image_pull_secrets", value)

    class BuilderContext(BuilderContextBase["BuildBuilderSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = BuildBuilderSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for BuildBuilderSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["BuildBuilderSpec", Builder]:
        return GenericListBuilder[BuildBuilderSpec, BuildBuilderSpec.Builder]()

    image: str | None = None
    image_pull_secrets: Annotated[
        list[LocalObjectReference] | None, Field(alias="imagePullSecrets")
    ] = None


class BuildStack(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["BuildStack"]:
            return BuildStack

        def build(self) -> "BuildStack":
            return BuildStack(**self._attrs)

        def id(self, value: str | None, /) -> Self:
            return self._set("id", value)

        def run_image(self, value: str | None, /) -> Self:
            return self._set("run_image", value)

    class BuilderContext(BuilderContextBase["BuildStack.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = BuildStack.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for BuildStack."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["BuildStack", Builder]:
        return GenericListBuilder[BuildStack, BuildStack.Builder]()

    id: str | None = None
    run_image: Annotated[str | None, Field(alias="runImage")] = None


class BuildpackInfo(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["BuildpackInfo"]:
            return BuildpackInfo

        def build(self) -> "BuildpackInfo":
            return BuildpackInfo(**self._attrs)

        def id(self, value: str, /) -> Self:
            return self._set("id", value)

        def version(self, value: str | None, /) -> Self:
            return self._set("version", value)

    class BuilderContext(BuilderContextBase["BuildpackInfo.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = BuildpackInfo.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for BuildpackInfo."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["BuildpackInfo", Builder]:
        return GenericListBuilder[BuildpackInfo, BuildpackInfo.Builder]()

    id: str = ""
    version: str | None = None


class BuildpackMetadata(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["BuildpackMetadata"]:
            return BuildpackMetadata

        def build(self) -> "BuildpackMetadata":
            return BuildpackMetadata(**self._attrs)

        def homepage(self, value: str | None, /) -> Self:
            return self._set("homepage", value)

        def id(self, value: str, /) -> Self:
            return self._set("id", value)

        def version(self, value: str, /) -> Self:
            return self._set("version", value)

    class BuilderContext(BuilderContextBase["BuildpackMetadata.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = BuildpackMetadata.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for BuildpackMetadata."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["BuildpackMetadata", Builder]:
        return GenericListBuilder[BuildpackMetadata, BuildpackMetadata.Builder]()

    homepage: str | None = None
    id: str = ""
    version: str = ""


class BuildpackRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["BuildpackRef"]:
            return BuildpackRef

        def build(self) -> "BuildpackRef":
            return BuildpackRef(**self._attrs)

        def id(self, value: str, /) -> Self:
            return self._set("id", value)

        def optional(self, value: bool | None, /) -> Self:
            return self._set("optional", value)

        def version(self, value: str | None, /) -> Self:
            return self._set("version", value)

    class BuilderContext(BuilderContextBase["BuildpackRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = BuildpackRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for BuildpackRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["BuildpackRef", Builder]:
        return GenericListBuilder[BuildpackRef, BuildpackRef.Builder]()

    id: str = ""
    optional: bool | None = None
    version: str | None = None


class BuildpackStack(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["BuildpackStack"]:
            return BuildpackStack

        def build(self) -> "BuildpackStack":
            return BuildpackStack(**self._attrs)

        def id(self, value: str, /) -> Self:
            return self._set("id", value)

        def mixins(self, value: list[str] | None, /) -> Self:
            return self._set("mixins", value)

    class BuilderContext(BuilderContextBase["BuildpackStack.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = BuildpackStack.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for BuildpackStack."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["BuildpackStack", Builder]:
        return GenericListBuilder[BuildpackStack, BuildpackStack.Builder]()

    id: str = ""
    mixins: list[str] | None = None


class BuildpackageInfo(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["BuildpackageInfo"]:
            return BuildpackageInfo

        def build(self) -> "BuildpackageInfo":
            return BuildpackageInfo(**self._attrs)

        def homepage(self, value: str | None, /) -> Self:
            return self._set("homepage", value)

        def id(self, value: str | None, /) -> Self:
            return self._set("id", value)

        def version(self, value: str | None, /) -> Self:
            return self._set("version", value)

    class BuilderContext(BuilderContextBase["BuildpackageInfo.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = BuildpackageInfo.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for BuildpackageInfo."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["BuildpackageInfo", Builder]:
        return GenericListBuilder[BuildpackageInfo, BuildpackageInfo.Builder]()

    homepage: str | None = None
    id: str | None = None
    version: str | None = None


class CNBBinding(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["CNBBinding"]:
            return CNBBinding

        def build(self) -> "CNBBinding":
            return CNBBinding(**self._attrs)

        @overload
        def metadata_ref(
            self, value_or_callback: LocalObjectReference | None, /
        ) -> "CNBBinding.Builder": ...

        @overload
        def metadata_ref(
            self,
            value_or_callback: Callable[
                [LocalObjectReference.Builder],
                LocalObjectReference.Builder | LocalObjectReference,
            ],
            /,
        ) -> "CNBBinding.Builder": ...

        @overload
        def metadata_ref(
            self, value_or_callback: Never = ...
        ) -> "LocalObjectReference.BuilderContext": ...

        def metadata_ref(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = LocalObjectReference.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(LocalObjectReference.builder())
                if isinstance(output, LocalObjectReference.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata_ref", value)

        def name(self, value: str | None, /) -> Self:
            return self._set("name", value)

        @overload
        def secret_ref(
            self, value_or_callback: LocalObjectReference | None, /
        ) -> "CNBBinding.Builder": ...

        @overload
        def secret_ref(
            self,
            value_or_callback: Callable[
                [LocalObjectReference.Builder],
                LocalObjectReference.Builder | LocalObjectReference,
            ],
            /,
        ) -> "CNBBinding.Builder": ...

        @overload
        def secret_ref(
            self, value_or_callback: Never = ...
        ) -> "LocalObjectReference.BuilderContext": ...

        def secret_ref(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = LocalObjectReference.BuilderContext()
                context._parent_builder = self
                context._field_name = "secret_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(LocalObjectReference.builder())
                if isinstance(output, LocalObjectReference.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("secret_ref", value)

    class BuilderContext(BuilderContextBase["CNBBinding.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = CNBBinding.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for CNBBinding."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["CNBBinding", Builder]:
        return GenericListBuilder[CNBBinding, CNBBinding.Builder]()

    metadata_ref: Annotated[LocalObjectReference | None, Field(alias="metadataRef")] = None
    name: str | None = None
    secret_ref: Annotated[LocalObjectReference | None, Field(alias="secretRef")] = None


class Condition(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Condition"]:
            return Condition

        def build(self) -> "Condition":
            return Condition(**self._attrs)

        def last_transition_time(self, value: str | None, /) -> Self:
            "LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant)."
            return self._set("last_transition_time", value)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def severity(self, value: str | None, /) -> Self:
            "Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error."
            return self._set("severity", value)

        def status(self, value: str, /) -> Self:
            "Status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of condition."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["Condition.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Condition.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Condition."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Condition", Builder]:
        return GenericListBuilder[Condition, Condition.Builder]()

    last_transition_time: Annotated[str | None, Field(alias="lastTransitionTime")] = None
    "LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant)."
    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    severity: str | None = None
    "Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error."
    status: str = ""
    "Status of the condition, one of True, False, Unknown."
    type: str = ""
    "Type of condition."


class Git(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Git"]:
            return Git

        def build(self) -> "Git":
            return Git(**self._attrs)

        def initialize_submodules(self, value: bool | None, /) -> Self:
            return self._set("initialize_submodules", value)

        def revision(self, value: str, /) -> Self:
            return self._set("revision", value)

        def url(self, value: str, /) -> Self:
            return self._set("url", value)

    class BuilderContext(BuilderContextBase["Git.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Git.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Git."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Git", Builder]:
        return GenericListBuilder[Git, Git.Builder]()

    initialize_submodules: Annotated[bool | None, Field(alias="initializeSubmodules")] = None
    revision: str = ""
    url: str = ""


class ImageSource(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ImageSource"]:
            return ImageSource

        def build(self) -> "ImageSource":
            return ImageSource(**self._attrs)

        def image(self, value: str | None, /) -> Self:
            return self._set("image", value)

    class BuilderContext(BuilderContextBase["ImageSource.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ImageSource.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ImageSource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ImageSource", Builder]:
        return GenericListBuilder[ImageSource, ImageSource.Builder]()

    image: str | None = None


class NotarySecretRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["NotarySecretRef"]:
            return NotarySecretRef

        def build(self) -> "NotarySecretRef":
            return NotarySecretRef(**self._attrs)

        def name(self, value: str, /) -> Self:
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["NotarySecretRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = NotarySecretRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for NotarySecretRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["NotarySecretRef", Builder]:
        return GenericListBuilder[NotarySecretRef, NotarySecretRef.Builder]()

    name: str = ""


class NotaryV1Config(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["NotaryV1Config"]:
            return NotaryV1Config

        def build(self) -> "NotaryV1Config":
            return NotaryV1Config(**self._attrs)

        @overload
        def secret_ref(self, value_or_callback: NotarySecretRef, /) -> "NotaryV1Config.Builder": ...

        @overload
        def secret_ref(
            self,
            value_or_callback: Callable[
                [NotarySecretRef.Builder], NotarySecretRef.Builder | NotarySecretRef
            ],
            /,
        ) -> "NotaryV1Config.Builder": ...

        @overload
        def secret_ref(
            self, value_or_callback: Never = ...
        ) -> "NotarySecretRef.BuilderContext": ...

        def secret_ref(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = NotarySecretRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "secret_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(NotarySecretRef.builder())
                if isinstance(output, NotarySecretRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("secret_ref", value)

        def url(self, value: str, /) -> Self:
            return self._set("url", value)

    class BuilderContext(BuilderContextBase["NotaryV1Config.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = NotaryV1Config.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for NotaryV1Config."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["NotaryV1Config", Builder]:
        return GenericListBuilder[NotaryV1Config, NotaryV1Config.Builder]()

    secret_ref: Annotated[NotarySecretRef, Field(alias="secretRef", validate_default=True)] = (
        NotarySecretRef.model_validate({})
    )
    url: str = ""


class OrderEntry(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["OrderEntry"]:
            return OrderEntry

        def build(self) -> "OrderEntry":
            return OrderEntry(**self._attrs)

        @overload
        def group(
            self, value_or_callback: list[BuildpackRef] | None, /
        ) -> "OrderEntry.Builder": ...

        @overload
        def group(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[BuildpackRef, BuildpackRef.Builder]],
                GenericListBuilder[BuildpackRef, BuildpackRef.Builder] | list[BuildpackRef],
            ],
            /,
        ) -> "OrderEntry.Builder": ...

        @overload
        def group(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[BuildpackRef.Builder]: ...

        def group(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[BuildpackRef.Builder]()
                context._parent_builder = self
                context._field_name = "group"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(BuildpackRef.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("group", value)

    class BuilderContext(BuilderContextBase["OrderEntry.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = OrderEntry.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for OrderEntry."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["OrderEntry", Builder]:
        return GenericListBuilder[OrderEntry, OrderEntry.Builder]()

    group: list[BuildpackRef] | None = None


class Registry(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Registry"]:
            return Registry

        def build(self) -> "Registry":
            return Registry(**self._attrs)

        def image(self, value: str, /) -> Self:
            return self._set("image", value)

        @overload
        def image_pull_secrets(
            self, value_or_callback: list[LocalObjectReference] | None, /
        ) -> "Registry.Builder": ...

        @overload
        def image_pull_secrets(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[LocalObjectReference, LocalObjectReference.Builder]],
                GenericListBuilder[LocalObjectReference, LocalObjectReference.Builder]
                | list[LocalObjectReference],
            ],
            /,
        ) -> "Registry.Builder": ...

        @overload
        def image_pull_secrets(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[LocalObjectReference.Builder]: ...

        def image_pull_secrets(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[LocalObjectReference.Builder]()
                context._parent_builder = self
                context._field_name = "image_pull_secrets"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(LocalObjectReference.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("image_pull_secrets", value)

    class BuilderContext(BuilderContextBase["Registry.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Registry.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Registry."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Registry", Builder]:
        return GenericListBuilder[Registry, Registry.Builder]()

    image: str = ""
    image_pull_secrets: Annotated[
        list[LocalObjectReference] | None, Field(alias="imagePullSecrets")
    ] = None


class ResolvedBlobSource(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ResolvedBlobSource"]:
            return ResolvedBlobSource

        def build(self) -> "ResolvedBlobSource":
            return ResolvedBlobSource(**self._attrs)

        def strip_components(self, value: int | None, /) -> Self:
            return self._set("strip_components", value)

        def sub_path(self, value: str | None, /) -> Self:
            return self._set("sub_path", value)

        def url(self, value: str, /) -> Self:
            return self._set("url", value)

    class BuilderContext(BuilderContextBase["ResolvedBlobSource.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ResolvedBlobSource.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ResolvedBlobSource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ResolvedBlobSource", Builder]:
        return GenericListBuilder[ResolvedBlobSource, ResolvedBlobSource.Builder]()

    strip_components: Annotated[int | None, Field(alias="stripComponents")] = None
    sub_path: Annotated[str | None, Field(alias="subPath")] = None
    url: str = ""


class ResolvedGitSource(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ResolvedGitSource"]:
            return ResolvedGitSource

        def build(self) -> "ResolvedGitSource":
            return ResolvedGitSource(**self._attrs)

        def initialize_submodules(self, value: bool | None, /) -> Self:
            return self._set("initialize_submodules", value)

        def revision(self, value: str, /) -> Self:
            return self._set("revision", value)

        def sub_path(self, value: str | None, /) -> Self:
            return self._set("sub_path", value)

        def type(self, value: str, /) -> Self:
            return self._set("type", value)

        def url(self, value: str, /) -> Self:
            return self._set("url", value)

    class BuilderContext(BuilderContextBase["ResolvedGitSource.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ResolvedGitSource.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ResolvedGitSource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ResolvedGitSource", Builder]:
        return GenericListBuilder[ResolvedGitSource, ResolvedGitSource.Builder]()

    initialize_submodules: Annotated[bool | None, Field(alias="initializeSubmodules")] = None
    revision: str = ""
    sub_path: Annotated[str | None, Field(alias="subPath")] = None
    type: str = ""
    url: str = ""


class ResolvedRegistrySource(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ResolvedRegistrySource"]:
            return ResolvedRegistrySource

        def build(self) -> "ResolvedRegistrySource":
            return ResolvedRegistrySource(**self._attrs)

        def image(self, value: str, /) -> Self:
            return self._set("image", value)

        @overload
        def image_pull_secrets(
            self, value_or_callback: list[LocalObjectReference] | None, /
        ) -> "ResolvedRegistrySource.Builder": ...

        @overload
        def image_pull_secrets(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[LocalObjectReference, LocalObjectReference.Builder]],
                GenericListBuilder[LocalObjectReference, LocalObjectReference.Builder]
                | list[LocalObjectReference],
            ],
            /,
        ) -> "ResolvedRegistrySource.Builder": ...

        @overload
        def image_pull_secrets(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[LocalObjectReference.Builder]: ...

        def image_pull_secrets(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[LocalObjectReference.Builder]()
                context._parent_builder = self
                context._field_name = "image_pull_secrets"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(LocalObjectReference.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("image_pull_secrets", value)

        def sub_path(self, value: str | None, /) -> Self:
            return self._set("sub_path", value)

    class BuilderContext(BuilderContextBase["ResolvedRegistrySource.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ResolvedRegistrySource.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ResolvedRegistrySource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ResolvedRegistrySource", Builder]:
        return GenericListBuilder[ResolvedRegistrySource, ResolvedRegistrySource.Builder]()

    image: str = ""
    image_pull_secrets: Annotated[
        list[LocalObjectReference] | None, Field(alias="imagePullSecrets")
    ] = None
    sub_path: Annotated[str | None, Field(alias="subPath")] = None


class ResolvedSourceConfig(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ResolvedSourceConfig"]:
            return ResolvedSourceConfig

        def build(self) -> "ResolvedSourceConfig":
            return ResolvedSourceConfig(**self._attrs)

        @overload
        def blob(
            self, value_or_callback: ResolvedBlobSource | None, /
        ) -> "ResolvedSourceConfig.Builder": ...

        @overload
        def blob(
            self,
            value_or_callback: Callable[
                [ResolvedBlobSource.Builder],
                ResolvedBlobSource.Builder | ResolvedBlobSource,
            ],
            /,
        ) -> "ResolvedSourceConfig.Builder": ...

        @overload
        def blob(self, value_or_callback: Never = ...) -> "ResolvedBlobSource.BuilderContext": ...

        def blob(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ResolvedBlobSource.BuilderContext()
                context._parent_builder = self
                context._field_name = "blob"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ResolvedBlobSource.builder())
                if isinstance(output, ResolvedBlobSource.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("blob", value)

        @overload
        def git(
            self, value_or_callback: ResolvedGitSource | None, /
        ) -> "ResolvedSourceConfig.Builder": ...

        @overload
        def git(
            self,
            value_or_callback: Callable[
                [ResolvedGitSource.Builder],
                ResolvedGitSource.Builder | ResolvedGitSource,
            ],
            /,
        ) -> "ResolvedSourceConfig.Builder": ...

        @overload
        def git(self, value_or_callback: Never = ...) -> "ResolvedGitSource.BuilderContext": ...

        def git(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ResolvedGitSource.BuilderContext()
                context._parent_builder = self
                context._field_name = "git"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ResolvedGitSource.builder())
                if isinstance(output, ResolvedGitSource.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("git", value)

        @overload
        def registry(
            self, value_or_callback: ResolvedRegistrySource | None, /
        ) -> "ResolvedSourceConfig.Builder": ...

        @overload
        def registry(
            self,
            value_or_callback: Callable[
                [ResolvedRegistrySource.Builder],
                ResolvedRegistrySource.Builder | ResolvedRegistrySource,
            ],
            /,
        ) -> "ResolvedSourceConfig.Builder": ...

        @overload
        def registry(
            self, value_or_callback: Never = ...
        ) -> "ResolvedRegistrySource.BuilderContext": ...

        def registry(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ResolvedRegistrySource.BuilderContext()
                context._parent_builder = self
                context._field_name = "registry"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ResolvedRegistrySource.builder())
                if isinstance(output, ResolvedRegistrySource.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("registry", value)

    class BuilderContext(BuilderContextBase["ResolvedSourceConfig.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ResolvedSourceConfig.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ResolvedSourceConfig."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ResolvedSourceConfig", Builder]:
        return GenericListBuilder[ResolvedSourceConfig, ResolvedSourceConfig.Builder]()

    blob: ResolvedBlobSource | None = None
    git: ResolvedGitSource | None = None
    registry: ResolvedRegistrySource | None = None


class SourceConfig(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SourceConfig"]:
            return SourceConfig

        def build(self) -> "SourceConfig":
            return SourceConfig(**self._attrs)

        @overload
        def blob(self, value_or_callback: Blob | None, /) -> "SourceConfig.Builder": ...

        @overload
        def blob(
            self, value_or_callback: Callable[[Blob.Builder], Blob.Builder | Blob], /
        ) -> "SourceConfig.Builder": ...

        @overload
        def blob(self, value_or_callback: Never = ...) -> "Blob.BuilderContext": ...

        def blob(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = Blob.BuilderContext()
                context._parent_builder = self
                context._field_name = "blob"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Blob.builder())
                if isinstance(output, Blob.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("blob", value)

        @overload
        def git(self, value_or_callback: Git | None, /) -> "SourceConfig.Builder": ...

        @overload
        def git(
            self, value_or_callback: Callable[[Git.Builder], Git.Builder | Git], /
        ) -> "SourceConfig.Builder": ...

        @overload
        def git(self, value_or_callback: Never = ...) -> "Git.BuilderContext": ...

        def git(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = Git.BuilderContext()
                context._parent_builder = self
                context._field_name = "git"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Git.builder())
                if isinstance(output, Git.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("git", value)

        @overload
        def registry(self, value_or_callback: Registry | None, /) -> "SourceConfig.Builder": ...

        @overload
        def registry(
            self,
            value_or_callback: Callable[[Registry.Builder], Registry.Builder | Registry],
            /,
        ) -> "SourceConfig.Builder": ...

        @overload
        def registry(self, value_or_callback: Never = ...) -> "Registry.BuilderContext": ...

        def registry(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = Registry.BuilderContext()
                context._parent_builder = self
                context._field_name = "registry"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Registry.builder())
                if isinstance(output, Registry.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("registry", value)

        def sub_path(self, value: str | None, /) -> Self:
            return self._set("sub_path", value)

    class BuilderContext(BuilderContextBase["SourceConfig.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SourceConfig.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SourceConfig."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SourceConfig", Builder]:
        return GenericListBuilder[SourceConfig, SourceConfig.Builder]()

    blob: Blob | None = None
    git: Git | None = None
    registry: Registry | None = None
    sub_path: Annotated[str | None, Field(alias="subPath")] = None


class Status(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Status"]:
            return Status

        def build(self) -> "Status":
            return Status(**self._attrs)

        @overload
        def conditions(self, value_or_callback: list[Condition] | None, /) -> "Status.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[Condition, Condition.Builder]],
                GenericListBuilder[Condition, Condition.Builder] | list[Condition],
            ],
            /,
        ) -> "Status.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[Condition.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions the latest available observations of a resource\u0027s current state."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[Condition.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Condition.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "ObservedGeneration is the \u0027Generation\u0027 of the Service that was last processed by the controller."
            return self._set("observed_generation", value)

    class BuilderContext(BuilderContextBase["Status.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Status.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Status."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Status", Builder]:
        return GenericListBuilder[Status, Status.Builder]()

    conditions: list[Condition] | None = None
    "Conditions the latest available observations of a resource\u0027s current state."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "ObservedGeneration is the \u0027Generation\u0027 of the Service that was last processed by the controller."


class VolatileTime(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["VolatileTime"]:
            return VolatileTime

        def build(self) -> "VolatileTime":
            return VolatileTime(**self._attrs)

        @overload
        def inner(self, value_or_callback: Time, /) -> "VolatileTime.Builder": ...

        @overload
        def inner(
            self, value_or_callback: Callable[[Time.Builder], Time.Builder | Time], /
        ) -> "VolatileTime.Builder": ...

        @overload
        def inner(self, value_or_callback: Never = ...) -> "Time.BuilderContext": ...

        def inner(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = Time.BuilderContext()
                context._parent_builder = self
                context._field_name = "inner"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Time.builder())
                if isinstance(output, Time.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("inner", value)

    class BuilderContext(BuilderContextBase["VolatileTime.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = VolatileTime.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for VolatileTime."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["VolatileTime", Builder]:
        return GenericListBuilder[VolatileTime, VolatileTime.Builder]()

    inner: Time


class BuildpackStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["BuildpackStatus"]:
            return BuildpackStatus

        def build(self) -> "BuildpackStatus":
            return BuildpackStatus(**self._attrs)

        def api(self, value: str | None, /) -> Self:
            return self._set("api", value)

        @overload
        def buildpackage(
            self, value_or_callback: BuildpackageInfo | None, /
        ) -> "BuildpackStatus.Builder": ...

        @overload
        def buildpackage(
            self,
            value_or_callback: Callable[
                [BuildpackageInfo.Builder], BuildpackageInfo.Builder | BuildpackageInfo
            ],
            /,
        ) -> "BuildpackStatus.Builder": ...

        @overload
        def buildpackage(
            self, value_or_callback: Never = ...
        ) -> "BuildpackageInfo.BuilderContext": ...

        def buildpackage(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = BuildpackageInfo.BuilderContext()
                context._parent_builder = self
                context._field_name = "buildpackage"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(BuildpackageInfo.builder())
                if isinstance(output, BuildpackageInfo.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("buildpackage", value)

        def diff_id(self, value: str | None, /) -> Self:
            return self._set("diff_id", value)

        def digest(self, value: str | None, /) -> Self:
            return self._set("digest", value)

        def homepage(self, value: str | None, /) -> Self:
            return self._set("homepage", value)

        def id(self, value: str, /) -> Self:
            return self._set("id", value)

        @overload
        def order(
            self, value_or_callback: list[OrderEntry] | None, /
        ) -> "BuildpackStatus.Builder": ...

        @overload
        def order(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[OrderEntry, OrderEntry.Builder]],
                GenericListBuilder[OrderEntry, OrderEntry.Builder] | list[OrderEntry],
            ],
            /,
        ) -> "BuildpackStatus.Builder": ...

        @overload
        def order(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[OrderEntry.Builder]: ...

        def order(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[OrderEntry.Builder]()
                context._parent_builder = self
                context._field_name = "order"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(OrderEntry.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("order", value)

        def size(self, value: int | None, /) -> Self:
            return self._set("size", value)

        @overload
        def stacks(
            self, value_or_callback: list[BuildpackStack] | None, /
        ) -> "BuildpackStatus.Builder": ...

        @overload
        def stacks(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[BuildpackStack, BuildpackStack.Builder]],
                GenericListBuilder[BuildpackStack, BuildpackStack.Builder] | list[BuildpackStack],
            ],
            /,
        ) -> "BuildpackStatus.Builder": ...

        @overload
        def stacks(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[BuildpackStack.Builder]: ...

        def stacks(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[BuildpackStack.Builder]()
                context._parent_builder = self
                context._field_name = "stacks"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(BuildpackStack.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("stacks", value)

        @overload
        def store_image(
            self, value_or_callback: ImageSource | None, /
        ) -> "BuildpackStatus.Builder": ...

        @overload
        def store_image(
            self,
            value_or_callback: Callable[[ImageSource.Builder], ImageSource.Builder | ImageSource],
            /,
        ) -> "BuildpackStatus.Builder": ...

        @overload
        def store_image(self, value_or_callback: Never = ...) -> "ImageSource.BuilderContext": ...

        def store_image(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ImageSource.BuilderContext()
                context._parent_builder = self
                context._field_name = "store_image"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ImageSource.builder())
                if isinstance(output, ImageSource.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("store_image", value)

        def version(self, value: str | None, /) -> Self:
            return self._set("version", value)

    class BuilderContext(BuilderContextBase["BuildpackStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = BuildpackStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for BuildpackStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["BuildpackStatus", Builder]:
        return GenericListBuilder[BuildpackStatus, BuildpackStatus.Builder]()

    api: str | None = None
    buildpackage: Annotated[BuildpackageInfo | None, Field(validate_default=True)] = (
        BuildpackageInfo.model_validate({})
    )
    diff_id: Annotated[str | None, Field(alias="diffId")] = None
    digest: str | None = None
    homepage: str | None = None
    id: str = ""
    order: list[OrderEntry] | None = None
    size: int | None = None
    stacks: list[BuildpackStack] | None = None
    store_image: Annotated[ImageSource | None, Field(alias="storeImage", validate_default=True)] = (
        ImageSource.model_validate({})
    )
    version: str | None = None


class NotaryConfig(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["NotaryConfig"]:
            return NotaryConfig

        def build(self) -> "NotaryConfig":
            return NotaryConfig(**self._attrs)

        @overload
        def v1(self, value_or_callback: NotaryV1Config | None, /) -> "NotaryConfig.Builder": ...

        @overload
        def v1(
            self,
            value_or_callback: Callable[
                [NotaryV1Config.Builder], NotaryV1Config.Builder | NotaryV1Config
            ],
            /,
        ) -> "NotaryConfig.Builder": ...

        @overload
        def v1(self, value_or_callback: Never = ...) -> "NotaryV1Config.BuilderContext": ...

        def v1(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = NotaryV1Config.BuilderContext()
                context._parent_builder = self
                context._field_name = "v1"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(NotaryV1Config.builder())
                if isinstance(output, NotaryV1Config.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("v1", value)

    class BuilderContext(BuilderContextBase["NotaryConfig.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = NotaryConfig.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for NotaryConfig."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["NotaryConfig", Builder]:
        return GenericListBuilder[NotaryConfig, NotaryConfig.Builder]()

    v1: NotaryV1Config | None = None
