# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import Annotated, Callable, overload

from cloudcoil.apimachinery import (
    LabelSelector,
    Quantity,
    Time,
)
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from pydantic import Field


class ConfigMapKeySelector(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ConfigMapKeySelector"]:
            return ConfigMapKeySelector

        def build(self) -> "ConfigMapKeySelector":
            return ConfigMapKeySelector(**self._attrs)

        def key(self, value: str, /) -> Self:
            "The key to select."
            return self._set("key", value)

        def name(self, value: str | None, /) -> Self:
            "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
            return self._set("name", value)

        def optional(self, value: bool | None, /) -> Self:
            "Specify whether the ConfigMap or it\u0027s key must be defined"
            return self._set("optional", value)

    class BuilderContext(BuilderContextBase["ConfigMapKeySelector.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ConfigMapKeySelector.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ConfigMapKeySelector."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ConfigMapKeySelector", Builder]:
        return GenericListBuilder[ConfigMapKeySelector, ConfigMapKeySelector.Builder]()

    key: str
    "The key to select."
    name: str | None = None
    "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
    optional: bool | None = None
    "Specify whether the ConfigMap or it\u0027s key must be defined"


class ContainerStateRunning(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ContainerStateRunning"]:
            return ContainerStateRunning

        def build(self) -> "ContainerStateRunning":
            return ContainerStateRunning(**self._attrs)

        @overload
        def started_at(
            self, value_or_callback: Time | None, /
        ) -> "ContainerStateRunning.Builder": ...

        @overload
        def started_at(
            self, value_or_callback: Callable[[Time.Builder], Time.Builder | Time], /
        ) -> "ContainerStateRunning.Builder": ...

        @overload
        def started_at(self, value_or_callback: Never = ...) -> "Time.BuilderContext": ...

        def started_at(self, value_or_callback=UNSET, /):
            "Time at which the container was last (re-)started"
            if self._in_context and value_or_callback is UNSET:
                context = Time.BuilderContext()
                context._parent_builder = self
                context._field_name = "started_at"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Time.builder())
                if isinstance(output, Time.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("started_at", value)

    class BuilderContext(BuilderContextBase["ContainerStateRunning.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ContainerStateRunning.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ContainerStateRunning."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ContainerStateRunning", Builder]:
        return GenericListBuilder[ContainerStateRunning, ContainerStateRunning.Builder]()

    started_at: Annotated[Time | None, Field(alias="startedAt")] = None
    "Time at which the container was last (re-)started"


class ContainerStateTerminated(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ContainerStateTerminated"]:
            return ContainerStateTerminated

        def build(self) -> "ContainerStateTerminated":
            return ContainerStateTerminated(**self._attrs)

        def container_id(self, value: str | None, /) -> Self:
            "Container\u0027s ID in the format \u0027docker://\u003ccontainer_id\u003e\u0027"
            return self._set("container_id", value)

        def exit_code(self, value: int, /) -> Self:
            "Exit status from the last termination of the container"
            return self._set("exit_code", value)

        @overload
        def finished_at(
            self, value_or_callback: Time | None, /
        ) -> "ContainerStateTerminated.Builder": ...

        @overload
        def finished_at(
            self, value_or_callback: Callable[[Time.Builder], Time.Builder | Time], /
        ) -> "ContainerStateTerminated.Builder": ...

        @overload
        def finished_at(self, value_or_callback: Never = ...) -> "Time.BuilderContext": ...

        def finished_at(self, value_or_callback=UNSET, /):
            "Time at which the container last terminated"
            if self._in_context and value_or_callback is UNSET:
                context = Time.BuilderContext()
                context._parent_builder = self
                context._field_name = "finished_at"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Time.builder())
                if isinstance(output, Time.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("finished_at", value)

        def message(self, value: str | None, /) -> Self:
            "Message regarding the last termination of the container"
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "(brief) reason from the last termination of the container"
            return self._set("reason", value)

        def signal(self, value: int | None, /) -> Self:
            "Signal from the last termination of the container"
            return self._set("signal", value)

        @overload
        def started_at(
            self, value_or_callback: Time | None, /
        ) -> "ContainerStateTerminated.Builder": ...

        @overload
        def started_at(
            self, value_or_callback: Callable[[Time.Builder], Time.Builder | Time], /
        ) -> "ContainerStateTerminated.Builder": ...

        @overload
        def started_at(self, value_or_callback: Never = ...) -> "Time.BuilderContext": ...

        def started_at(self, value_or_callback=UNSET, /):
            "Time at which previous execution of the container started"
            if self._in_context and value_or_callback is UNSET:
                context = Time.BuilderContext()
                context._parent_builder = self
                context._field_name = "started_at"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Time.builder())
                if isinstance(output, Time.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("started_at", value)

    class BuilderContext(BuilderContextBase["ContainerStateTerminated.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ContainerStateTerminated.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ContainerStateTerminated."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ContainerStateTerminated", Builder]:
        return GenericListBuilder[ContainerStateTerminated, ContainerStateTerminated.Builder]()

    container_id: Annotated[str | None, Field(alias="containerID")] = None
    "Container\u0027s ID in the format \u0027docker://\u003ccontainer_id\u003e\u0027"
    exit_code: Annotated[int, Field(alias="exitCode")]
    "Exit status from the last termination of the container"
    finished_at: Annotated[Time | None, Field(alias="finishedAt")] = None
    "Time at which the container last terminated"
    message: str | None = None
    "Message regarding the last termination of the container"
    reason: str | None = None
    "(brief) reason from the last termination of the container"
    signal: int | None = None
    "Signal from the last termination of the container"
    started_at: Annotated[Time | None, Field(alias="startedAt")] = None
    "Time at which previous execution of the container started"


class ContainerStateWaiting(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ContainerStateWaiting"]:
            return ContainerStateWaiting

        def build(self) -> "ContainerStateWaiting":
            return ContainerStateWaiting(**self._attrs)

        def message(self, value: str | None, /) -> Self:
            "Message regarding why the container is not yet running."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "(brief) reason the container is not yet running."
            return self._set("reason", value)

    class BuilderContext(BuilderContextBase["ContainerStateWaiting.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ContainerStateWaiting.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ContainerStateWaiting."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ContainerStateWaiting", Builder]:
        return GenericListBuilder[ContainerStateWaiting, ContainerStateWaiting.Builder]()

    message: str | None = None
    "Message regarding why the container is not yet running."
    reason: str | None = None
    "(brief) reason the container is not yet running."


class LocalObjectReference(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["LocalObjectReference"]:
            return LocalObjectReference

        def build(self) -> "LocalObjectReference":
            return LocalObjectReference(**self._attrs)

        def name(self, value: str | None, /) -> Self:
            "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["LocalObjectReference.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = LocalObjectReference.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for LocalObjectReference."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["LocalObjectReference", Builder]:
        return GenericListBuilder[LocalObjectReference, LocalObjectReference.Builder]()

    name: str | None = None
    "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"


class NodeSelectorRequirement(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["NodeSelectorRequirement"]:
            return NodeSelectorRequirement

        def build(self) -> "NodeSelectorRequirement":
            return NodeSelectorRequirement(**self._attrs)

        def key(self, value: str, /) -> Self:
            "The label key that the selector applies to."
            return self._set("key", value)

        def operator(self, value: str, /) -> Self:
            "Represents a key\u0027s relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt."
            return self._set("operator", value)

        def values(self, value: list[str] | None, /) -> Self:
            "An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch."
            return self._set("values", value)

    class BuilderContext(BuilderContextBase["NodeSelectorRequirement.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = NodeSelectorRequirement.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for NodeSelectorRequirement."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["NodeSelectorRequirement", Builder]:
        return GenericListBuilder[NodeSelectorRequirement, NodeSelectorRequirement.Builder]()

    key: str
    "The label key that the selector applies to."
    operator: str
    "Represents a key\u0027s relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt."
    values: list[str] | None = None
    "An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch."


class NodeSelectorTerm(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["NodeSelectorTerm"]:
            return NodeSelectorTerm

        def build(self) -> "NodeSelectorTerm":
            return NodeSelectorTerm(**self._attrs)

        @overload
        def match_expressions(
            self, value_or_callback: list[NodeSelectorRequirement] | None, /
        ) -> "NodeSelectorTerm.Builder": ...

        @overload
        def match_expressions(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[NodeSelectorRequirement, NodeSelectorRequirement.Builder]],
                GenericListBuilder[NodeSelectorRequirement, NodeSelectorRequirement.Builder]
                | list[NodeSelectorRequirement],
            ],
            /,
        ) -> "NodeSelectorTerm.Builder": ...

        @overload
        def match_expressions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[NodeSelectorRequirement.Builder]: ...

        def match_expressions(self, value_or_callback=UNSET, /):
            "A list of node selector requirements by node\u0027s labels."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[NodeSelectorRequirement.Builder]()
                context._parent_builder = self
                context._field_name = "match_expressions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(NodeSelectorRequirement.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("match_expressions", value)

        @overload
        def match_fields(
            self, value_or_callback: list[NodeSelectorRequirement] | None, /
        ) -> "NodeSelectorTerm.Builder": ...

        @overload
        def match_fields(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[NodeSelectorRequirement, NodeSelectorRequirement.Builder]],
                GenericListBuilder[NodeSelectorRequirement, NodeSelectorRequirement.Builder]
                | list[NodeSelectorRequirement],
            ],
            /,
        ) -> "NodeSelectorTerm.Builder": ...

        @overload
        def match_fields(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[NodeSelectorRequirement.Builder]: ...

        def match_fields(self, value_or_callback=UNSET, /):
            "A list of node selector requirements by node\u0027s fields."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[NodeSelectorRequirement.Builder]()
                context._parent_builder = self
                context._field_name = "match_fields"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(NodeSelectorRequirement.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("match_fields", value)

    class BuilderContext(BuilderContextBase["NodeSelectorTerm.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = NodeSelectorTerm.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for NodeSelectorTerm."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["NodeSelectorTerm", Builder]:
        return GenericListBuilder[NodeSelectorTerm, NodeSelectorTerm.Builder]()

    match_expressions: Annotated[
        list[NodeSelectorRequirement] | None, Field(alias="matchExpressions")
    ] = None
    "A list of node selector requirements by node\u0027s labels."
    match_fields: Annotated[list[NodeSelectorRequirement] | None, Field(alias="matchFields")] = None
    "A list of node selector requirements by node\u0027s fields."


class ObjectFieldSelector(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ObjectFieldSelector"]:
            return ObjectFieldSelector

        def build(self) -> "ObjectFieldSelector":
            return ObjectFieldSelector(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            'Version of the schema the FieldPath is written in terms of, defaults to "v1".'
            return self._set("api_version", value)

        def field_path(self, value: str, /) -> Self:
            "Path of the field to select in the specified API version."
            return self._set("field_path", value)

    class BuilderContext(BuilderContextBase["ObjectFieldSelector.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ObjectFieldSelector.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ObjectFieldSelector."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ObjectFieldSelector", Builder]:
        return GenericListBuilder[ObjectFieldSelector, ObjectFieldSelector.Builder]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    'Version of the schema the FieldPath is written in terms of, defaults to "v1".'
    field_path: Annotated[str, Field(alias="fieldPath")]
    "Path of the field to select in the specified API version."


class ObjectReference(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ObjectReference"]:
            return ObjectReference

        def build(self) -> "ObjectReference":
            return ObjectReference(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def field_path(self, value: str | None, /) -> Self:
            'If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: "spec.containers{name}" (where "name" refers to the name of the container that triggered the event) or if no container name is specified "spec.containers[2]" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object.'
            return self._set("field_path", value)

        def kind(self, value: str | None, /) -> Self:
            "Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
            return self._set("kind", value)

        def name(self, value: str | None, /) -> Self:
            "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"
            return self._set("namespace", value)

        def resource_version(self, value: str | None, /) -> Self:
            "Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency"
            return self._set("resource_version", value)

        def uid(self, value: str | None, /) -> Self:
            "UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"
            return self._set("uid", value)

    class BuilderContext(BuilderContextBase["ObjectReference.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ObjectReference.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ObjectReference."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ObjectReference", Builder]:
        return GenericListBuilder[ObjectReference, ObjectReference.Builder]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent."
    field_path: Annotated[str | None, Field(alias="fieldPath")] = None
    'If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: "spec.containers{name}" (where "name" refers to the name of the container that triggered the event) or if no container name is specified "spec.containers[2]" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object.'
    kind: str | None = None
    "Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
    name: str | None = None
    "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
    namespace: str | None = None
    "Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"
    resource_version: Annotated[str | None, Field(alias="resourceVersion")] = None
    "Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency"
    uid: str | None = None
    "UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"


class PodAffinityTerm(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PodAffinityTerm"]:
            return PodAffinityTerm

        def build(self) -> "PodAffinityTerm":
            return PodAffinityTerm(**self._attrs)

        @overload
        def label_selector(
            self, value_or_callback: LabelSelector | None, /
        ) -> "PodAffinityTerm.Builder": ...

        @overload
        def label_selector(
            self,
            value_or_callback: Callable[
                [LabelSelector.Builder], LabelSelector.Builder | LabelSelector
            ],
            /,
        ) -> "PodAffinityTerm.Builder": ...

        @overload
        def label_selector(
            self, value_or_callback: Never = ...
        ) -> "LabelSelector.BuilderContext": ...

        def label_selector(self, value_or_callback=UNSET, /):
            "A label query over a set of resources, in this case pods."
            if self._in_context and value_or_callback is UNSET:
                context = LabelSelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "label_selector"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(LabelSelector.builder())
                if isinstance(output, LabelSelector.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("label_selector", value)

        @overload
        def namespace_selector(
            self, value_or_callback: LabelSelector | None, /
        ) -> "PodAffinityTerm.Builder": ...

        @overload
        def namespace_selector(
            self,
            value_or_callback: Callable[
                [LabelSelector.Builder], LabelSelector.Builder | LabelSelector
            ],
            /,
        ) -> "PodAffinityTerm.Builder": ...

        @overload
        def namespace_selector(
            self, value_or_callback: Never = ...
        ) -> "LabelSelector.BuilderContext": ...

        def namespace_selector(self, value_or_callback=UNSET, /):
            'A label query over the set of namespaces that the term applies to. The term is applied to the union of the namespaces selected by this field and the ones listed in the namespaces field. null selector and null or empty namespaces list means "this pod\u0027s namespace". An empty selector ({}) matches all namespaces. This field is beta-level and is only honored when PodAffinityNamespaceSelector feature is enabled.'
            if self._in_context and value_or_callback is UNSET:
                context = LabelSelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "namespace_selector"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(LabelSelector.builder())
                if isinstance(output, LabelSelector.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("namespace_selector", value)

        def namespaces(self, value: list[str] | None, /) -> Self:
            'namespaces specifies a static list of namespace names that the term applies to. The term is applied to the union of the namespaces listed in this field and the ones selected by namespaceSelector. null or empty namespaces list and null namespaceSelector means "this pod\u0027s namespace"'
            return self._set("namespaces", value)

        def topology_key(self, value: str, /) -> Self:
            "This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the selected pods is running. Empty topologyKey is not allowed."
            return self._set("topology_key", value)

    class BuilderContext(BuilderContextBase["PodAffinityTerm.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PodAffinityTerm.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PodAffinityTerm."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PodAffinityTerm", Builder]:
        return GenericListBuilder[PodAffinityTerm, PodAffinityTerm.Builder]()

    label_selector: Annotated[LabelSelector | None, Field(alias="labelSelector")] = None
    "A label query over a set of resources, in this case pods."
    namespace_selector: Annotated[LabelSelector | None, Field(alias="namespaceSelector")] = None
    'A label query over the set of namespaces that the term applies to. The term is applied to the union of the namespaces selected by this field and the ones listed in the namespaces field. null selector and null or empty namespaces list means "this pod\u0027s namespace". An empty selector ({}) matches all namespaces. This field is beta-level and is only honored when PodAffinityNamespaceSelector feature is enabled.'
    namespaces: list[str] | None = None
    'namespaces specifies a static list of namespace names that the term applies to. The term is applied to the union of the namespaces listed in this field and the ones selected by namespaceSelector. null or empty namespaces list and null namespaceSelector means "this pod\u0027s namespace"'
    topology_key: Annotated[str, Field(alias="topologyKey")]
    "This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the selected pods is running. Empty topologyKey is not allowed."


class PreferredSchedulingTerm(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PreferredSchedulingTerm"]:
            return PreferredSchedulingTerm

        def build(self) -> "PreferredSchedulingTerm":
            return PreferredSchedulingTerm(**self._attrs)

        @overload
        def preference(
            self, value_or_callback: NodeSelectorTerm, /
        ) -> "PreferredSchedulingTerm.Builder": ...

        @overload
        def preference(
            self,
            value_or_callback: Callable[
                [NodeSelectorTerm.Builder], NodeSelectorTerm.Builder | NodeSelectorTerm
            ],
            /,
        ) -> "PreferredSchedulingTerm.Builder": ...

        @overload
        def preference(
            self, value_or_callback: Never = ...
        ) -> "NodeSelectorTerm.BuilderContext": ...

        def preference(self, value_or_callback=UNSET, /):
            "A node selector term, associated with the corresponding weight."
            if self._in_context and value_or_callback is UNSET:
                context = NodeSelectorTerm.BuilderContext()
                context._parent_builder = self
                context._field_name = "preference"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(NodeSelectorTerm.builder())
                if isinstance(output, NodeSelectorTerm.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("preference", value)

        def weight(self, value: int, /) -> Self:
            "Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100."
            return self._set("weight", value)

    class BuilderContext(BuilderContextBase["PreferredSchedulingTerm.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PreferredSchedulingTerm.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PreferredSchedulingTerm."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PreferredSchedulingTerm", Builder]:
        return GenericListBuilder[PreferredSchedulingTerm, PreferredSchedulingTerm.Builder]()

    preference: NodeSelectorTerm
    "A node selector term, associated with the corresponding weight."
    weight: int
    "Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100."


class ResourceFieldSelector(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ResourceFieldSelector"]:
            return ResourceFieldSelector

        def build(self) -> "ResourceFieldSelector":
            return ResourceFieldSelector(**self._attrs)

        def container_name(self, value: str | None, /) -> Self:
            "Container name: required for volumes, optional for env vars"
            return self._set("container_name", value)

        @overload
        def divisor(
            self, value_or_callback: Quantity | None, /
        ) -> "ResourceFieldSelector.Builder": ...

        @overload
        def divisor(
            self,
            value_or_callback: Callable[[Quantity.Builder], Quantity.Builder | Quantity],
            /,
        ) -> "ResourceFieldSelector.Builder": ...

        @overload
        def divisor(self, value_or_callback: Never = ...) -> "Quantity.BuilderContext": ...

        def divisor(self, value_or_callback=UNSET, /):
            'Specifies the output format of the exposed resources, defaults to "1"'
            if self._in_context and value_or_callback is UNSET:
                context = Quantity.BuilderContext()
                context._parent_builder = self
                context._field_name = "divisor"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(Quantity.builder())
                if isinstance(output, Quantity.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("divisor", value)

        def resource(self, value: str, /) -> Self:
            "Required: resource to select"
            return self._set("resource", value)

    class BuilderContext(BuilderContextBase["ResourceFieldSelector.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ResourceFieldSelector.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ResourceFieldSelector."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ResourceFieldSelector", Builder]:
        return GenericListBuilder[ResourceFieldSelector, ResourceFieldSelector.Builder]()

    container_name: Annotated[str | None, Field(alias="containerName")] = None
    "Container name: required for volumes, optional for env vars"
    divisor: Quantity | None = None
    'Specifies the output format of the exposed resources, defaults to "1"'
    resource: str
    "Required: resource to select"


class ResourceRequirements(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ResourceRequirements"]:
            return ResourceRequirements

        def build(self) -> "ResourceRequirements":
            return ResourceRequirements(**self._attrs)

        def limits(self, value: dict[str, Quantity] | None, /) -> Self:
            "Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/"
            return self._set("limits", value)

        def requests(self, value: dict[str, Quantity] | None, /) -> Self:
            "Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/"
            return self._set("requests", value)

    class BuilderContext(BuilderContextBase["ResourceRequirements.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ResourceRequirements.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ResourceRequirements."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ResourceRequirements", Builder]:
        return GenericListBuilder[ResourceRequirements, ResourceRequirements.Builder]()

    limits: dict[str, Quantity] | None = None
    "Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/"
    requests: dict[str, Quantity] | None = None
    "Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/"


class SecretKeySelector(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SecretKeySelector"]:
            return SecretKeySelector

        def build(self) -> "SecretKeySelector":
            return SecretKeySelector(**self._attrs)

        def key(self, value: str, /) -> Self:
            "The key of the secret to select from.  Must be a valid secret key."
            return self._set("key", value)

        def name(self, value: str | None, /) -> Self:
            "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
            return self._set("name", value)

        def optional(self, value: bool | None, /) -> Self:
            "Specify whether the Secret or it\u0027s key must be defined"
            return self._set("optional", value)

    class BuilderContext(BuilderContextBase["SecretKeySelector.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SecretKeySelector.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SecretKeySelector."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SecretKeySelector", Builder]:
        return GenericListBuilder[SecretKeySelector, SecretKeySelector.Builder]()

    key: str
    "The key of the secret to select from.  Must be a valid secret key."
    name: str | None = None
    "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
    optional: bool | None = None
    "Specify whether the Secret or it\u0027s key must be defined"


class Toleration(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Toleration"]:
            return Toleration

        def build(self) -> "Toleration":
            return Toleration(**self._attrs)

        def effect(self, value: str | None, /) -> Self:
            "Effect indicates the taint effect to match. Empty means match all taint effects. When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute."
            return self._set("effect", value)

        def key(self, value: str | None, /) -> Self:
            "Key is the taint key that the toleration applies to. Empty means match all taint keys. If the key is empty, operator must be Exists; this combination means to match all values and all keys."
            return self._set("key", value)

        def operator(self, value: str | None, /) -> Self:
            "Operator represents a key\u0027s relationship to the value. Valid operators are Exists and Equal. Defaults to Equal. Exists is equivalent to wildcard for value, so that a pod can tolerate all taints of a particular category."
            return self._set("operator", value)

        def toleration_seconds(self, value: int | None, /) -> Self:
            "TolerationSeconds represents the period of time the toleration (which must be of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default, it is not set, which means tolerate the taint forever (do not evict). Zero and negative values will be treated as 0 (evict immediately) by the system."
            return self._set("toleration_seconds", value)

        def value(self, value: str | None, /) -> Self:
            "Value is the taint value the toleration matches to. If the operator is Exists, the value should be empty, otherwise just a regular string."
            return self._set("value", value)

    class BuilderContext(BuilderContextBase["Toleration.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Toleration.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Toleration."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Toleration", Builder]:
        return GenericListBuilder[Toleration, Toleration.Builder]()

    effect: str | None = None
    "Effect indicates the taint effect to match. Empty means match all taint effects. When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute."
    key: str | None = None
    "Key is the taint key that the toleration applies to. Empty means match all taint keys. If the key is empty, operator must be Exists; this combination means to match all values and all keys."
    operator: str | None = None
    "Operator represents a key\u0027s relationship to the value. Valid operators are Exists and Equal. Defaults to Equal. Exists is equivalent to wildcard for value, so that a pod can tolerate all taints of a particular category."
    toleration_seconds: Annotated[int | None, Field(alias="tolerationSeconds")] = None
    "TolerationSeconds represents the period of time the toleration (which must be of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default, it is not set, which means tolerate the taint forever (do not evict). Zero and negative values will be treated as 0 (evict immediately) by the system."
    value: str | None = None
    "Value is the taint value the toleration matches to. If the operator is Exists, the value should be empty, otherwise just a regular string."


class WeightedPodAffinityTerm(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["WeightedPodAffinityTerm"]:
            return WeightedPodAffinityTerm

        def build(self) -> "WeightedPodAffinityTerm":
            return WeightedPodAffinityTerm(**self._attrs)

        @overload
        def pod_affinity_term(
            self, value_or_callback: PodAffinityTerm, /
        ) -> "WeightedPodAffinityTerm.Builder": ...

        @overload
        def pod_affinity_term(
            self,
            value_or_callback: Callable[
                [PodAffinityTerm.Builder], PodAffinityTerm.Builder | PodAffinityTerm
            ],
            /,
        ) -> "WeightedPodAffinityTerm.Builder": ...

        @overload
        def pod_affinity_term(
            self, value_or_callback: Never = ...
        ) -> "PodAffinityTerm.BuilderContext": ...

        def pod_affinity_term(self, value_or_callback=UNSET, /):
            "Required. A pod affinity term, associated with the corresponding weight."
            if self._in_context and value_or_callback is UNSET:
                context = PodAffinityTerm.BuilderContext()
                context._parent_builder = self
                context._field_name = "pod_affinity_term"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PodAffinityTerm.builder())
                if isinstance(output, PodAffinityTerm.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("pod_affinity_term", value)

        def weight(self, value: int, /) -> Self:
            "weight associated with matching the corresponding podAffinityTerm, in the range 1-100."
            return self._set("weight", value)

    class BuilderContext(BuilderContextBase["WeightedPodAffinityTerm.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = WeightedPodAffinityTerm.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for WeightedPodAffinityTerm."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["WeightedPodAffinityTerm", Builder]:
        return GenericListBuilder[WeightedPodAffinityTerm, WeightedPodAffinityTerm.Builder]()

    pod_affinity_term: Annotated[PodAffinityTerm, Field(alias="podAffinityTerm")]
    "Required. A pod affinity term, associated with the corresponding weight."
    weight: int
    "weight associated with matching the corresponding podAffinityTerm, in the range 1-100."


class ContainerState(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ContainerState"]:
            return ContainerState

        def build(self) -> "ContainerState":
            return ContainerState(**self._attrs)

        @overload
        def running(
            self, value_or_callback: ContainerStateRunning | None, /
        ) -> "ContainerState.Builder": ...

        @overload
        def running(
            self,
            value_or_callback: Callable[
                [ContainerStateRunning.Builder],
                ContainerStateRunning.Builder | ContainerStateRunning,
            ],
            /,
        ) -> "ContainerState.Builder": ...

        @overload
        def running(
            self, value_or_callback: Never = ...
        ) -> "ContainerStateRunning.BuilderContext": ...

        def running(self, value_or_callback=UNSET, /):
            "Details about a running container"
            if self._in_context and value_or_callback is UNSET:
                context = ContainerStateRunning.BuilderContext()
                context._parent_builder = self
                context._field_name = "running"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ContainerStateRunning.builder())
                if isinstance(output, ContainerStateRunning.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("running", value)

        @overload
        def terminated(
            self, value_or_callback: ContainerStateTerminated | None, /
        ) -> "ContainerState.Builder": ...

        @overload
        def terminated(
            self,
            value_or_callback: Callable[
                [ContainerStateTerminated.Builder],
                ContainerStateTerminated.Builder | ContainerStateTerminated,
            ],
            /,
        ) -> "ContainerState.Builder": ...

        @overload
        def terminated(
            self, value_or_callback: Never = ...
        ) -> "ContainerStateTerminated.BuilderContext": ...

        def terminated(self, value_or_callback=UNSET, /):
            "Details about a terminated container"
            if self._in_context and value_or_callback is UNSET:
                context = ContainerStateTerminated.BuilderContext()
                context._parent_builder = self
                context._field_name = "terminated"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ContainerStateTerminated.builder())
                if isinstance(output, ContainerStateTerminated.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("terminated", value)

        @overload
        def waiting(
            self, value_or_callback: ContainerStateWaiting | None, /
        ) -> "ContainerState.Builder": ...

        @overload
        def waiting(
            self,
            value_or_callback: Callable[
                [ContainerStateWaiting.Builder],
                ContainerStateWaiting.Builder | ContainerStateWaiting,
            ],
            /,
        ) -> "ContainerState.Builder": ...

        @overload
        def waiting(
            self, value_or_callback: Never = ...
        ) -> "ContainerStateWaiting.BuilderContext": ...

        def waiting(self, value_or_callback=UNSET, /):
            "Details about a waiting container"
            if self._in_context and value_or_callback is UNSET:
                context = ContainerStateWaiting.BuilderContext()
                context._parent_builder = self
                context._field_name = "waiting"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ContainerStateWaiting.builder())
                if isinstance(output, ContainerStateWaiting.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("waiting", value)

    class BuilderContext(BuilderContextBase["ContainerState.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ContainerState.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ContainerState."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ContainerState", Builder]:
        return GenericListBuilder[ContainerState, ContainerState.Builder]()

    running: ContainerStateRunning | None = None
    "Details about a running container"
    terminated: ContainerStateTerminated | None = None
    "Details about a terminated container"
    waiting: ContainerStateWaiting | None = None
    "Details about a waiting container"


class EnvVarSource(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EnvVarSource"]:
            return EnvVarSource

        def build(self) -> "EnvVarSource":
            return EnvVarSource(**self._attrs)

        @overload
        def config_map_key_ref(
            self, value_or_callback: ConfigMapKeySelector | None, /
        ) -> "EnvVarSource.Builder": ...

        @overload
        def config_map_key_ref(
            self,
            value_or_callback: Callable[
                [ConfigMapKeySelector.Builder],
                ConfigMapKeySelector.Builder | ConfigMapKeySelector,
            ],
            /,
        ) -> "EnvVarSource.Builder": ...

        @overload
        def config_map_key_ref(
            self, value_or_callback: Never = ...
        ) -> "ConfigMapKeySelector.BuilderContext": ...

        def config_map_key_ref(self, value_or_callback=UNSET, /):
            "Selects a key of a ConfigMap."
            if self._in_context and value_or_callback is UNSET:
                context = ConfigMapKeySelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "config_map_key_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ConfigMapKeySelector.builder())
                if isinstance(output, ConfigMapKeySelector.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("config_map_key_ref", value)

        @overload
        def field_ref(
            self, value_or_callback: ObjectFieldSelector | None, /
        ) -> "EnvVarSource.Builder": ...

        @overload
        def field_ref(
            self,
            value_or_callback: Callable[
                [ObjectFieldSelector.Builder],
                ObjectFieldSelector.Builder | ObjectFieldSelector,
            ],
            /,
        ) -> "EnvVarSource.Builder": ...

        @overload
        def field_ref(
            self, value_or_callback: Never = ...
        ) -> "ObjectFieldSelector.BuilderContext": ...

        def field_ref(self, value_or_callback=UNSET, /):
            "Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP."
            if self._in_context and value_or_callback is UNSET:
                context = ObjectFieldSelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "field_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectFieldSelector.builder())
                if isinstance(output, ObjectFieldSelector.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("field_ref", value)

        @overload
        def resource_field_ref(
            self, value_or_callback: ResourceFieldSelector | None, /
        ) -> "EnvVarSource.Builder": ...

        @overload
        def resource_field_ref(
            self,
            value_or_callback: Callable[
                [ResourceFieldSelector.Builder],
                ResourceFieldSelector.Builder | ResourceFieldSelector,
            ],
            /,
        ) -> "EnvVarSource.Builder": ...

        @overload
        def resource_field_ref(
            self, value_or_callback: Never = ...
        ) -> "ResourceFieldSelector.BuilderContext": ...

        def resource_field_ref(self, value_or_callback=UNSET, /):
            "Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported."
            if self._in_context and value_or_callback is UNSET:
                context = ResourceFieldSelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "resource_field_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ResourceFieldSelector.builder())
                if isinstance(output, ResourceFieldSelector.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("resource_field_ref", value)

        @overload
        def secret_key_ref(
            self, value_or_callback: SecretKeySelector | None, /
        ) -> "EnvVarSource.Builder": ...

        @overload
        def secret_key_ref(
            self,
            value_or_callback: Callable[
                [SecretKeySelector.Builder],
                SecretKeySelector.Builder | SecretKeySelector,
            ],
            /,
        ) -> "EnvVarSource.Builder": ...

        @overload
        def secret_key_ref(
            self, value_or_callback: Never = ...
        ) -> "SecretKeySelector.BuilderContext": ...

        def secret_key_ref(self, value_or_callback=UNSET, /):
            "Selects a key of a secret in the pod\u0027s namespace"
            if self._in_context and value_or_callback is UNSET:
                context = SecretKeySelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "secret_key_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SecretKeySelector.builder())
                if isinstance(output, SecretKeySelector.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("secret_key_ref", value)

    class BuilderContext(BuilderContextBase["EnvVarSource.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EnvVarSource.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EnvVarSource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["EnvVarSource", Builder]:
        return GenericListBuilder[EnvVarSource, EnvVarSource.Builder]()

    config_map_key_ref: Annotated[ConfigMapKeySelector | None, Field(alias="configMapKeyRef")] = (
        None
    )
    "Selects a key of a ConfigMap."
    field_ref: Annotated[ObjectFieldSelector | None, Field(alias="fieldRef")] = None
    "Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP."
    resource_field_ref: Annotated[ResourceFieldSelector | None, Field(alias="resourceFieldRef")] = (
        None
    )
    "Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported."
    secret_key_ref: Annotated[SecretKeySelector | None, Field(alias="secretKeyRef")] = None
    "Selects a key of a secret in the pod\u0027s namespace"


class NodeSelector(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["NodeSelector"]:
            return NodeSelector

        def build(self) -> "NodeSelector":
            return NodeSelector(**self._attrs)

        @overload
        def node_selector_terms(
            self, value_or_callback: list[NodeSelectorTerm], /
        ) -> "NodeSelector.Builder": ...

        @overload
        def node_selector_terms(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[NodeSelectorTerm, NodeSelectorTerm.Builder]],
                GenericListBuilder[NodeSelectorTerm, NodeSelectorTerm.Builder]
                | list[NodeSelectorTerm],
            ],
            /,
        ) -> "NodeSelector.Builder": ...

        @overload
        def node_selector_terms(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[NodeSelectorTerm.Builder]: ...

        def node_selector_terms(self, value_or_callback=UNSET, /):
            "Required. A list of node selector terms. The terms are ORed."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[NodeSelectorTerm.Builder]()
                context._parent_builder = self
                context._field_name = "node_selector_terms"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(NodeSelectorTerm.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("node_selector_terms", value)

    class BuilderContext(BuilderContextBase["NodeSelector.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = NodeSelector.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for NodeSelector."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["NodeSelector", Builder]:
        return GenericListBuilder[NodeSelector, NodeSelector.Builder]()

    node_selector_terms: Annotated[list[NodeSelectorTerm], Field(alias="nodeSelectorTerms")]
    "Required. A list of node selector terms. The terms are ORed."


class PodAffinity(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PodAffinity"]:
            return PodAffinity

        def build(self) -> "PodAffinity":
            return PodAffinity(**self._attrs)

        @overload
        def preferred_during_scheduling_ignored_during_execution(
            self, value_or_callback: list[WeightedPodAffinityTerm] | None, /
        ) -> "PodAffinity.Builder": ...

        @overload
        def preferred_during_scheduling_ignored_during_execution(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[WeightedPodAffinityTerm, WeightedPodAffinityTerm.Builder]],
                GenericListBuilder[WeightedPodAffinityTerm, WeightedPodAffinityTerm.Builder]
                | list[WeightedPodAffinityTerm],
            ],
            /,
        ) -> "PodAffinity.Builder": ...

        @overload
        def preferred_during_scheduling_ignored_during_execution(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[WeightedPodAffinityTerm.Builder]: ...

        def preferred_during_scheduling_ignored_during_execution(self, value_or_callback=UNSET, /):
            'The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node has pods which matches the corresponding podAffinityTerm; the node(s) with the highest sum are the most preferred.'
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[WeightedPodAffinityTerm.Builder]()
                context._parent_builder = self
                context._field_name = "preferred_during_scheduling_ignored_during_execution"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(WeightedPodAffinityTerm.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("preferred_during_scheduling_ignored_during_execution", value)

        @overload
        def required_during_scheduling_ignored_during_execution(
            self, value_or_callback: list[PodAffinityTerm] | None, /
        ) -> "PodAffinity.Builder": ...

        @overload
        def required_during_scheduling_ignored_during_execution(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[PodAffinityTerm, PodAffinityTerm.Builder]],
                GenericListBuilder[PodAffinityTerm, PodAffinityTerm.Builder]
                | list[PodAffinityTerm],
            ],
            /,
        ) -> "PodAffinity.Builder": ...

        @overload
        def required_during_scheduling_ignored_during_execution(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[PodAffinityTerm.Builder]: ...

        def required_during_scheduling_ignored_during_execution(self, value_or_callback=UNSET, /):
            "If the affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to a pod label update), the system may or may not try to eventually evict the pod from its node. When there are multiple elements, the lists of nodes corresponding to each podAffinityTerm are intersected, i.e. all terms must be satisfied."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[PodAffinityTerm.Builder]()
                context._parent_builder = self
                context._field_name = "required_during_scheduling_ignored_during_execution"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PodAffinityTerm.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("required_during_scheduling_ignored_during_execution", value)

    class BuilderContext(BuilderContextBase["PodAffinity.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PodAffinity.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PodAffinity."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PodAffinity", Builder]:
        return GenericListBuilder[PodAffinity, PodAffinity.Builder]()

    preferred_during_scheduling_ignored_during_execution: Annotated[
        list[WeightedPodAffinityTerm] | None,
        Field(alias="preferredDuringSchedulingIgnoredDuringExecution"),
    ] = None
    'The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node has pods which matches the corresponding podAffinityTerm; the node(s) with the highest sum are the most preferred.'
    required_during_scheduling_ignored_during_execution: Annotated[
        list[PodAffinityTerm] | None,
        Field(alias="requiredDuringSchedulingIgnoredDuringExecution"),
    ] = None
    "If the affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to a pod label update), the system may or may not try to eventually evict the pod from its node. When there are multiple elements, the lists of nodes corresponding to each podAffinityTerm are intersected, i.e. all terms must be satisfied."


class PodAntiAffinity(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PodAntiAffinity"]:
            return PodAntiAffinity

        def build(self) -> "PodAntiAffinity":
            return PodAntiAffinity(**self._attrs)

        @overload
        def preferred_during_scheduling_ignored_during_execution(
            self, value_or_callback: list[WeightedPodAffinityTerm] | None, /
        ) -> "PodAntiAffinity.Builder": ...

        @overload
        def preferred_during_scheduling_ignored_during_execution(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[WeightedPodAffinityTerm, WeightedPodAffinityTerm.Builder]],
                GenericListBuilder[WeightedPodAffinityTerm, WeightedPodAffinityTerm.Builder]
                | list[WeightedPodAffinityTerm],
            ],
            /,
        ) -> "PodAntiAffinity.Builder": ...

        @overload
        def preferred_during_scheduling_ignored_during_execution(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[WeightedPodAffinityTerm.Builder]: ...

        def preferred_during_scheduling_ignored_during_execution(self, value_or_callback=UNSET, /):
            'The scheduler will prefer to schedule pods to nodes that satisfy the anti-affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling anti-affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node has pods which matches the corresponding podAffinityTerm; the node(s) with the highest sum are the most preferred.'
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[WeightedPodAffinityTerm.Builder]()
                context._parent_builder = self
                context._field_name = "preferred_during_scheduling_ignored_during_execution"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(WeightedPodAffinityTerm.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("preferred_during_scheduling_ignored_during_execution", value)

        @overload
        def required_during_scheduling_ignored_during_execution(
            self, value_or_callback: list[PodAffinityTerm] | None, /
        ) -> "PodAntiAffinity.Builder": ...

        @overload
        def required_during_scheduling_ignored_during_execution(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[PodAffinityTerm, PodAffinityTerm.Builder]],
                GenericListBuilder[PodAffinityTerm, PodAffinityTerm.Builder]
                | list[PodAffinityTerm],
            ],
            /,
        ) -> "PodAntiAffinity.Builder": ...

        @overload
        def required_during_scheduling_ignored_during_execution(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[PodAffinityTerm.Builder]: ...

        def required_during_scheduling_ignored_during_execution(self, value_or_callback=UNSET, /):
            "If the anti-affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the anti-affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to a pod label update), the system may or may not try to eventually evict the pod from its node. When there are multiple elements, the lists of nodes corresponding to each podAffinityTerm are intersected, i.e. all terms must be satisfied."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[PodAffinityTerm.Builder]()
                context._parent_builder = self
                context._field_name = "required_during_scheduling_ignored_during_execution"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PodAffinityTerm.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("required_during_scheduling_ignored_during_execution", value)

    class BuilderContext(BuilderContextBase["PodAntiAffinity.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PodAntiAffinity.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PodAntiAffinity."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PodAntiAffinity", Builder]:
        return GenericListBuilder[PodAntiAffinity, PodAntiAffinity.Builder]()

    preferred_during_scheduling_ignored_during_execution: Annotated[
        list[WeightedPodAffinityTerm] | None,
        Field(alias="preferredDuringSchedulingIgnoredDuringExecution"),
    ] = None
    'The scheduler will prefer to schedule pods to nodes that satisfy the anti-affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling anti-affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node has pods which matches the corresponding podAffinityTerm; the node(s) with the highest sum are the most preferred.'
    required_during_scheduling_ignored_during_execution: Annotated[
        list[PodAffinityTerm] | None,
        Field(alias="requiredDuringSchedulingIgnoredDuringExecution"),
    ] = None
    "If the anti-affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the anti-affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to a pod label update), the system may or may not try to eventually evict the pod from its node. When there are multiple elements, the lists of nodes corresponding to each podAffinityTerm are intersected, i.e. all terms must be satisfied."


class EnvVar(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EnvVar"]:
            return EnvVar

        def build(self) -> "EnvVar":
            return EnvVar(**self._attrs)

        def name(self, value: str, /) -> Self:
            "Name of the environment variable. Must be a C_IDENTIFIER."
            return self._set("name", value)

        def value(self, value: str | None, /) -> Self:
            'Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to "".'
            return self._set("value", value)

        @overload
        def value_from(self, value_or_callback: EnvVarSource | None, /) -> "EnvVar.Builder": ...

        @overload
        def value_from(
            self,
            value_or_callback: Callable[
                [EnvVarSource.Builder], EnvVarSource.Builder | EnvVarSource
            ],
            /,
        ) -> "EnvVar.Builder": ...

        @overload
        def value_from(self, value_or_callback: Never = ...) -> "EnvVarSource.BuilderContext": ...

        def value_from(self, value_or_callback=UNSET, /):
            "Source for the environment variable\u0027s value. Cannot be used if value is not empty."
            if self._in_context and value_or_callback is UNSET:
                context = EnvVarSource.BuilderContext()
                context._parent_builder = self
                context._field_name = "value_from"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(EnvVarSource.builder())
                if isinstance(output, EnvVarSource.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("value_from", value)

    class BuilderContext(BuilderContextBase["EnvVar.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EnvVar.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EnvVar."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["EnvVar", Builder]:
        return GenericListBuilder[EnvVar, EnvVar.Builder]()

    name: str
    "Name of the environment variable. Must be a C_IDENTIFIER."
    value: str | None = None
    'Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to "".'
    value_from: Annotated[EnvVarSource | None, Field(alias="valueFrom")] = None
    "Source for the environment variable\u0027s value. Cannot be used if value is not empty."


class NodeAffinity(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["NodeAffinity"]:
            return NodeAffinity

        def build(self) -> "NodeAffinity":
            return NodeAffinity(**self._attrs)

        @overload
        def preferred_during_scheduling_ignored_during_execution(
            self, value_or_callback: list[PreferredSchedulingTerm] | None, /
        ) -> "NodeAffinity.Builder": ...

        @overload
        def preferred_during_scheduling_ignored_during_execution(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[PreferredSchedulingTerm, PreferredSchedulingTerm.Builder]],
                GenericListBuilder[PreferredSchedulingTerm, PreferredSchedulingTerm.Builder]
                | list[PreferredSchedulingTerm],
            ],
            /,
        ) -> "NodeAffinity.Builder": ...

        @overload
        def preferred_during_scheduling_ignored_during_execution(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[PreferredSchedulingTerm.Builder]: ...

        def preferred_during_scheduling_ignored_during_execution(self, value_or_callback=UNSET, /):
            'The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node matches the corresponding matchExpressions; the node(s) with the highest sum are the most preferred.'
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[PreferredSchedulingTerm.Builder]()
                context._parent_builder = self
                context._field_name = "preferred_during_scheduling_ignored_during_execution"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PreferredSchedulingTerm.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("preferred_during_scheduling_ignored_during_execution", value)

        @overload
        def required_during_scheduling_ignored_during_execution(
            self, value_or_callback: NodeSelector | None, /
        ) -> "NodeAffinity.Builder": ...

        @overload
        def required_during_scheduling_ignored_during_execution(
            self,
            value_or_callback: Callable[
                [NodeSelector.Builder], NodeSelector.Builder | NodeSelector
            ],
            /,
        ) -> "NodeAffinity.Builder": ...

        @overload
        def required_during_scheduling_ignored_during_execution(
            self, value_or_callback: Never = ...
        ) -> "NodeSelector.BuilderContext": ...

        def required_during_scheduling_ignored_during_execution(self, value_or_callback=UNSET, /):
            "If the affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to an update), the system may or may not try to eventually evict the pod from its node."
            if self._in_context and value_or_callback is UNSET:
                context = NodeSelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "required_during_scheduling_ignored_during_execution"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(NodeSelector.builder())
                if isinstance(output, NodeSelector.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("required_during_scheduling_ignored_during_execution", value)

    class BuilderContext(BuilderContextBase["NodeAffinity.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = NodeAffinity.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for NodeAffinity."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["NodeAffinity", Builder]:
        return GenericListBuilder[NodeAffinity, NodeAffinity.Builder]()

    preferred_during_scheduling_ignored_during_execution: Annotated[
        list[PreferredSchedulingTerm] | None,
        Field(alias="preferredDuringSchedulingIgnoredDuringExecution"),
    ] = None
    'The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node matches the corresponding matchExpressions; the node(s) with the highest sum are the most preferred.'
    required_during_scheduling_ignored_during_execution: Annotated[
        NodeSelector | None,
        Field(alias="requiredDuringSchedulingIgnoredDuringExecution"),
    ] = None
    "If the affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to an update), the system may or may not try to eventually evict the pod from its node."


class Affinity(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Affinity"]:
            return Affinity

        def build(self) -> "Affinity":
            return Affinity(**self._attrs)

        @overload
        def node_affinity(
            self, value_or_callback: NodeAffinity | None, /
        ) -> "Affinity.Builder": ...

        @overload
        def node_affinity(
            self,
            value_or_callback: Callable[
                [NodeAffinity.Builder], NodeAffinity.Builder | NodeAffinity
            ],
            /,
        ) -> "Affinity.Builder": ...

        @overload
        def node_affinity(
            self, value_or_callback: Never = ...
        ) -> "NodeAffinity.BuilderContext": ...

        def node_affinity(self, value_or_callback=UNSET, /):
            "Describes node affinity scheduling rules for the pod."
            if self._in_context and value_or_callback is UNSET:
                context = NodeAffinity.BuilderContext()
                context._parent_builder = self
                context._field_name = "node_affinity"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(NodeAffinity.builder())
                if isinstance(output, NodeAffinity.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("node_affinity", value)

        @overload
        def pod_affinity(self, value_or_callback: PodAffinity | None, /) -> "Affinity.Builder": ...

        @overload
        def pod_affinity(
            self,
            value_or_callback: Callable[[PodAffinity.Builder], PodAffinity.Builder | PodAffinity],
            /,
        ) -> "Affinity.Builder": ...

        @overload
        def pod_affinity(self, value_or_callback: Never = ...) -> "PodAffinity.BuilderContext": ...

        def pod_affinity(self, value_or_callback=UNSET, /):
            "Describes pod affinity scheduling rules (e.g. co-locate this pod in the same node, zone, etc. as some other pod(s))."
            if self._in_context and value_or_callback is UNSET:
                context = PodAffinity.BuilderContext()
                context._parent_builder = self
                context._field_name = "pod_affinity"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PodAffinity.builder())
                if isinstance(output, PodAffinity.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("pod_affinity", value)

        @overload
        def pod_anti_affinity(
            self, value_or_callback: PodAntiAffinity | None, /
        ) -> "Affinity.Builder": ...

        @overload
        def pod_anti_affinity(
            self,
            value_or_callback: Callable[
                [PodAntiAffinity.Builder], PodAntiAffinity.Builder | PodAntiAffinity
            ],
            /,
        ) -> "Affinity.Builder": ...

        @overload
        def pod_anti_affinity(
            self, value_or_callback: Never = ...
        ) -> "PodAntiAffinity.BuilderContext": ...

        def pod_anti_affinity(self, value_or_callback=UNSET, /):
            "Describes pod anti-affinity scheduling rules (e.g. avoid putting this pod in the same node, zone, etc. as some other pod(s))."
            if self._in_context and value_or_callback is UNSET:
                context = PodAntiAffinity.BuilderContext()
                context._parent_builder = self
                context._field_name = "pod_anti_affinity"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PodAntiAffinity.builder())
                if isinstance(output, PodAntiAffinity.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("pod_anti_affinity", value)

    class BuilderContext(BuilderContextBase["Affinity.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Affinity.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Affinity."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Affinity", Builder]:
        return GenericListBuilder[Affinity, Affinity.Builder]()

    node_affinity: Annotated[NodeAffinity | None, Field(alias="nodeAffinity")] = None
    "Describes node affinity scheduling rules for the pod."
    pod_affinity: Annotated[PodAffinity | None, Field(alias="podAffinity")] = None
    "Describes pod affinity scheduling rules (e.g. co-locate this pod in the same node, zone, etc. as some other pod(s))."
    pod_anti_affinity: Annotated[PodAntiAffinity | None, Field(alias="podAntiAffinity")] = None
    "Describes pod anti-affinity scheduling rules (e.g. avoid putting this pod in the same node, zone, etc. as some other pod(s))."
